FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /src
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

RUN addgroup -S md287 && adduser -S md287 -G md287
COPY --from=build /src/target/*.jar app.jar
RUN chown md287:md287 /app/app.jar

USER md287
EXPOSE 8083

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
